### ISSUE TITLE
occasional display issue for Voltage and Power

### ISSUE THREAD

**Issue by meiskam** [CrazyBoyFeng/AccSettings#3]
idk if this is from acc or accSettings, but once or twice per minute these show these values with the wrong order of magnitude

![vlc_seVQcNGdYb](https://user-images.githubusercontent.com/634802/145022533-50a35900-5651-4cb8-adfe-34d69f5af816.png)

(btw love the app, much better than going into the terminal)

**Comment by CrazyBoyFeng** [comment]
`AccSettings` formats the output of the `acc --info` command to show `VOLTAGE_NOW` and `POWER_NOW`. So this issue may need to be submitted to `acc` for resolution.  
However, if the problem is not very impactful and very rare, ignoring it is probably the most efficient thing to do.

@VR-25 What is your comment? Does this need to be followed up?

**Comment by CrazyBoyFeng** [comment]
According to the description, this problem occurs occasionally. The implication is that it tends to occur only for a moment and then quickly returns to normal.  
Although he didn't say so, I guess this problem occurred when he/she was staying on the `AccSettings` screen and didn't do anything. That's why he could observe the problem.

If this device is not a bad device, or used in an environment prone to static electricity. Then there is a possibility that its circuit does not have a capacitor for stabilizing the voltage and current, or the capacitor is damaged, so that the static electricity cannot be filtered out.  
But I don't know how to verify this.

**Comment by meiskam** [comment]
discharging:
```
Battery Service
  Max charging current: 0

Uevent
  BATT_FULL_CURRENT=640000
  CHARGE_TERM_CURRENT=-230
  CONSTANT_CHARGE_CURRENT=0
  CONSTANT_CHARGE_CURRENT_MAX=4500000
  CURRENT_AVG=-57373
  CURRENT_AVG=57373
  CURRENT_NOW=-91247
  CURRENT_NOW=296936
  INPUT_CURRENT_LIMITED=0
  CURRENT_NOW=-0.091247 Amps
```

charging:
```
Battery Service
  Max charging current: 1500000

Uevent
  BATT_FULL_CURRENT=640000
  CHARGE_TERM_CURRENT=-230
  CONSTANT_CHARGE_CURRENT=3230000
  CONSTANT_CHARGE_CURRENT_MAX=3100000
  CURRENT_AVG=-1307679
  CURRENT_AVG=1307679
  CURRENT_NOW=-1050415
  CURRENT_NOW=1050415
  INPUT_CURRENT_LIMITED=0
  INPUT_CURRENT_LIMITED=1
  CURRENT_NOW=1.05042 Amps
```

nothing seemed off when I tried to catch it when the app showed abnormal numbers, but i ran `watch acc -i curr` for a while and found a few like this:
```
Battery Service
  Max charging current: 0

Uevent
  BATT_FULL_CURRENT=640000
  CHARGE_TERM_CURRENT=-230
  CONSTANT_CHARGE_CURRENT=0
  CONSTANT_CHARGE_CURRENT_MAX=4500000
  CURRENT_AVG=-80871
  CURRENT_AVG=80871
  CURRENT_NOW=-8239
  CURRENT_NOW=8239
  INPUT_CURRENT_LIMITED=0
  CURRENT_NOW=-8.239 Amps
```

here's the raw output of that watch: https://pastebin.com/uZAvdvdx

**Comment by VR-25** [comment]
@meiskam , the logic for determining the correct unit for current and voltage is fairly simple.
```
if value == 0
  multiplier=1 // unit is irrelevant here
else if value < 10000
  multiplier=1000 // milliamps
else
  multiplier=1000000 // microamps
```
That said, it's prone to errors – but only under fairly rare circumstances.
Moving on, I don't believe your phone was drawing a current that low (CURRENT_NOW=-8239). ~8mAclearly  indicates a device fault, just like @CrazyBoyFeng suggested.
The good news is that the solution is simple: you just have to set ampere factor to 1000000 (6 zeroes, uA, according to the outputs you shared). This can easily be done in ACC Settings (the app): configuration > miscellaneous > advanced > ampere factor (kudos to @CrazyBoyFeng  for supporting even the more _obscure_ acc settings). Alternatively, you can run `acc --set amp_factor=1000000`.
